USERNAME='root'
PASSWORD='F7vZ3sL6oP9fj14'
SERVER='localhost'
DB='flask'
PORT='3305'

SQLALCHEMY_DATABASE_URI=f'mysql://{USERNAME}:{PASSWORD}@{SERVER}:{PORT}/{DB}'
print(SQLALCHEMY_DATABASE_URI)
SQLALCHEMY_TRACK_MODIFICATIONS=True

SECRET_KEY='chave_secreta1'
